use_frameworks!

target 'AlisterSwift_Example' do
  pod 'AlisterSwift', :path => '../'

  target 'AlisterSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
