use_frameworks!
platform :ios, '10.0'

target 'AlisterSwift_Example' do
  pod 'AlisterSwift', :path => '../'
  pod 'SnapKit'
  pod 'SwiftLint'
  
  target 'AlisterSwift_Tests' do
    inherit! :search_paths
  end
end
