line_length: 130
function_body_length: 50
vertical_whitespace: 2
opt_in_rules:
  - force_unwrapping
  - attributes
  - empty_count
disabled_rules:
  - identifier_name
  - trailing_whitespace
  - void_return #need to clarify
  - multiple_closures_with_trailing_closure
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Tests
  - Templates
