line_length: 130
function_body_length: 50
vertical_whitespace:
  max_empty_lines: 2
opt_in_rules:
  - force_unwrapping
  - attributes
  - empty_count
  - yoda_condition
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - unneeded_break_in_switch
  - unavailable_function
  - single_test_class

disabled_rules:
  - identifier_name
  - trailing_whitespace
  - void_return #need to clarify
  - multiple_closures_with_trailing_closure
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods/Nimble
  - Pods/Quick
  - Pods/SnapKit
  - Pods/SwiftLint
  # - Tests
  - Templates

